[project]
name = "amazon-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "preetha-pallavi", email = "preethamishra76@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "fastparquet>=2026.5.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=6.0.0",
    "streamlit>=1.59.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
amazon-review = "amazon_review:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
